### ISSUE TITLE
PB dépendances sur RPI 4.

### ISSUE THREAD

**Issue by edgd1er** [impulsio/MerosSync#3]
Bonjour,

Sur mon rpi4 j'ai une erreur lors de l'installation des dépendances. (rpi4 + conteneur debian buster)
```
import _cffi_backend as backend
    ImportError: /tmp/pip-build-env-j_2gbh1_/lib/python3.7/site-packages/_cffi_backend.cpython-37m-aarch64-linux-gnu.so: failed to map segment from shared object
```

le pb a été réglé par un pip3 install --upgrade pip3, en trois minutes, j'avais mes trois prises merioss MSS310 détectées et affichées. Merci.

Pour l'instant l'upgrade pip semble ne pas avoir avoir d'effets négatifs sur les autres plugins.  (j'ai fais l'upgrade pour le pip et pip3)

Je ne m'y connais pas assez en python pour savoir si le problème vient de mon installation.

Le code pourrait il prevoir le cas et proposer via un message dans le log l'upgrade du pip ?

**Comment by impulsio** [comment]
Bonjour,

Merci pour cette remontée d'information. Je vais regarder cela de plus près
!

Bonne journée
Jérôme

**Comment by impulsio** [comment]
Bonjour,

Pourrais-tu m'indiquer à quel moment cela s'est produit dans l'installation
des dépendances ? Ou me donner la log complète ?

Merci

Le lun. 28 nov. 2022, 10:57, Jérôme Rousseau ***@***.***> a
écrit :

> Bonjour,
>
> Merci pour cette remontée d'information. Je vais regarder cela de plus
> près !
>
> Bonne journée
> Jérôme
>

**Comment by edgd1er** [comment]
Bonjour,

La ligne qui genere l'erreur est:
https://github.com/impulsio/MerosSync/blob/27b2813ea0cdf430a55f26d986649eeafa5af80e/resources/install_apt.sh#L25

J'ai effacé le log d'installation, mais j'avais toujours une console avec les tests d'install en ligne de commande:
```
root@6d090c824b6a:/var/www/html/plugins/MerosSync/resources# python3 -m pip install pycares      
Collecting pycares
  Using cached https://files.pythonhosted.org/packages/ac/a3/21594384c2398420dd7f6e8656aeb5a2c15128ddf2b85ef5f4403342e18d/pycares-4.2.2.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s2h2_j_m/pycares/setup.py", line 54, in <module>
        zip_safe         = False
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/setuptools/dist.py", line 479, in __init__
        for k, v in attrs.items()
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/setuptools/dist.py", line 899, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/setuptools/dist.py", line 919, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_cares.py", line 604, in <module>
        ffi = cffi.FFI()
      File "/tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: /tmp/pip-build-env-toys0kaz/lib/python3.7/site-packages/_cffi_backend.cpython-37m-aarch64-linux-gnu.so: failed to map segment from shared object
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-s2h2_j_m/pycares/
```

**Comment by impulsio** [comment]
Bonjour,
C'est corrigé via commit https://github.com/impulsio/MerosSync/commit/7be36b2c3070e4a4ff15b9831d62d19798fe242b
Merci à toi
Bonne journée,
Jérôme

**Comment by impulsio** [comment]
Corrigé via https://github.com/impulsio/MerosSync/commit/02dfc50e16e9a9afcd7853d51eb1eed23ce2c047

**Comment by edgd1er** [comment]
Merci pour la correction et pour le plugin. J'ai un équipement assez capricieux qui ne comprend que les reboot éléctriques quand il plante, pas super bon, mais sinon je devrais m'en débarrasser, entre deux reboots, il marche bien.

**Comment by impulsio** [comment]
Je t'en prie ! Bon courage !
