### ISSUE TITLE
Callback api version

### ISSUE THREAD

**Issue by nicolasrata** [impulsio/MerosSync#7]
Bonjour,
Petit souci depuis quelques jours, potentiellement lié à la mise à jour en V2 de paho mqtt.

[paho mqtt V2](https://github.com/eclipse/paho.mqtt.python/releases/tag/v2.0.0)

`[2024-02-16 09:40:03][ERROR][DemonPython] : __init__() missing 1 required positional argument: 'callback_api_version'
Exception ignored in: <function Client.__del__ at 0x7f2fba8adaf0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
[2024-02-16 09:40:03][ERROR][DemonPython] : aSyncMeross Failed: __init__() missing 1 required positional argument: 'callback_api_version'
[2024-02-16 09:40:03][ERROR] : Aucun équipement connecté ou problème de connexion. Merci de consulter la log.
`

**Comment by impulsio** [comment]
Bonjour @nicolasrata ,
Effectivement je vois qu'une nouvelle version du plugin que j'utilise semble corriger la compatibilité. Je vais essayer ça en beta et je te tiendrai au courant.
Bonne journée

**Comment by impulsio** [comment]
Bonjour @nicolasrata 
Je viens de publier une nouvelle version. n'hésites pas à la mettre à jour et à mettre à jour les dépendances.
Cela devrait corriger le problème.
Bonne journée,
Jérôme

**Comment by impulsio** [comment]
![image](https://github.com/impulsio/MerosSync/assets/33810912/0756cd03-f0ac-4ccd-80f7-17979b1c5a7e)

**Comment by impulsio** [comment]
Au plaisir ! Bonne journée
